### ISSUE TITLE
Mundo onde Pode usar Fly

### ISSUE THREAD

**Issue by Animexpvp** [eduardo-mior/System#1]
https://github.com/RUSHyoutuber/System/blob/e7864d4f1f94e0999b9c3a2ee2119eff4cccd121/src/rush/comandos/ComandoFly.java#L69

No seu está assim 
List<String> worlds = ConfigManager.getConfig("mensagens").getStringList("Mundos-Onde-Pode-Usar-Fly");

erro:
ele não esta indentificando, qual mundo pode usar fly

correto:
List<String> worlds = ConfigManager.getConfig("settings").getStringList("Mundos-Onde-Pode-Usar-Fly");

obs: ele está no settings.yml e não está no mensagens!

**Comment by RUSHyoutuber** [comment]
Obrigado pelo aviso! Hoje quando eu fui revisar o código eu percebi que estava errado, ai agora quando eu entro no gitHub eu percebo que mais alguém notou isso haha. Obrigado!

**Comment by eduardo-mior** [comment]
Obrigado pelo aviso! Hoje quando eu fui revisar o código eu percebi que estava errado, ai agora quando eu entro no gitHub eu percebo que mais alguém notou isso haha. Obrigado!
PS: Até semana que vem eu atualiza os meus projetos!
