### ISSUE TITLE
Windows Deteta a nova versão como virus!

### ISSUE THREAD

**Issue by itsjaof** [eduardo-mior/System#14]
Segue uma print abaixo da deteção
![print](https://user-images.githubusercontent.com/73834828/132047372-a0b80cc3-bb30-4b2a-afb9-0fe478cceb1d.png)

**Comment by eduardo-mior** [comment]
É só essa nova versão 1.14.18 que ele esta detectando como virus ou as antigas 1.14.17 e 1.14.16 ele detectava também?

**Comment by itsjaof** [comment]
Eu já baixei outras, nenhuma detetou...

**Comment by eduardo-mior** [comment]
Não faço ideia doque possa estar acontecendo... Eu gerei essa versão exatamente do mesmo jeito que eu gero, com o mesmo computador, mesma IDE etc, não fiz nada de diferente, então sei oque pode ser porque ninguém mais reclamou além de você.

**Comment by eduardo-mior** [comment]
Você baixou na gamersboard a JAR ou baixou de algum outro lugar?

**Comment by itsjaof** [comment]
baixei direto do github

**Comment by eduardo-mior** [comment]
Não faço ideia então doque pode ser e porque ele detecta como vírus, qualquer coisa você mesmo pode baixar a source e você mesmo pode compilar

**Comment by eduardo-mior** [comment]
Fechando a issue porque o problema só acontece em alguns computadores específicos, e como o system não é um vírus o ideal é simplesmente ignorar a mensagem.
