### ISSUE TITLE
a versão mais recente do system é considerada como virus pelo anti-virus do windows..

### ISSUE THREAD

**Issue by ghost** [eduardo-mior/System#16]
![Screenshot_136](https://user-images.githubusercontent.com/75075207/134954005-6d182d7e-6eaf-4304-bc14-4affed992cdb.png)

**Comment by eduardo-mior** [comment]
Não faço ideia doque possa estar acontecendo... Eu gerei essa versão exatamente do mesmo jeito que eu gero, com o mesmo computador, mesma IDE etc, não fiz nada de diferente, então sei oque pode ser.

Pelo que vi na internet na internet isso aconteceu com outros plugins de senvolvdores.

Você baixou pela Gamersboard o System ou por aonde você baixou?

**Comment by ghost** [comment]
Baixei pelo próprio GitHub. Desculpa pela demora para responder.

**Comment by eduardo-mior** [comment]
@64xbits  Não faço ideia então doque pode ser e porque ele detecta como vírus, qualquer coisa você mesmo pode baixar a source e você mesmo pode compilar. Fiz varios testes em varios computadores e não detectou como virus.

**Comment by eduardo-mior** [comment]
Fechando a issue porque o problema só acontece em alguns computadores específicos, e como o system não é um vírus o ideal é simplesmente ignorar a mensagem.
