### ISSUE TITLE
Depois que eu uso o /warp, um erro aparece no chat e eu não consigo usar nem o chat local, nem o global, porém eu consigo usar outros comandos e modificar o mundo.

### ISSUE THREAD

**Issue by ghost** [eduardo-mior/System#17]
Não sei se isso acontece porque a chunk que a warp está setada está descarrega ou se a warp está setada em coordenadas que não são números inteiros.
(Percebi que o /tp do System é diferente do /tp do Minecraft, por isso setei as coordenadas com o tp do Minecraft. Exemplo: Digitando /tp 750 64 750, o System teleporta para 750,0 64,0 750,0 enquanto o comando padrão do Minecraft teleporta para o meio do bloco, 750,5 64,0 750,5. Por isso desconfio se só posso usar coordenadas de números inteiros para setar warps.)

Erro no console:
[erro warp.txt](https://github.com/eduardo-mior/System/files/7530990/erro.warp.txt)

Video mostrando o erro:
https://youtu.be/F2n62oXKCdo

**Comment by eduardo-mior** [comment]
Aparentemente esse erro esta sendo causado por algum outro plugin, da pra perceber isso na segunda linha do erro:
`	at IiIIIiiIIIiIiI.dispatch(Unknown Source) ~[?:?]
`

Se possível tenta ligar o servidor só com o System, sem nenhum outro plugin, e testa se funciona.

Depois disso vai colocando 1 por 1 dos plugins no servidor até achar oque ta com problema!
