### ISSUE TITLE
Não consigo colocar blocos ou quebrar blocos com o plugin

### ISSUE THREAD

**Issue by ghost** [eduardo-mior/System#19]
Estou criando aqui um servidor de survival mas configurei tudo, não achei nada nas settings que desabilita-se isso, não consigo quebrar blocos sem op ou permissões.

**Comment by eduardo-mior** [comment]
@Fehype isso é problema no WorldGuard o ou em outro plugin, o system não tem nada haver com isso, pode ser até configuração do servidor

**Comment by eduardo-mior** [comment]
@Fehype se puder mandar mais informações do problema aqui talvez eu possa debugar melhor, por hora irei fechar a issue.
