### ISSUE TITLE
Funções novas

### ISSUE THREAD

**Issue by joaoespanhol** [eduardo-mior/System#20]
Boas,

Adicionar canal local e global.
Sistema de caixa.
Banir item
Limpar o chão e as entidades x em x tempo (exemplo: clearlag)
System login e register
____________________________________
Criar como fosse um mod.

como exemplo: FTB essentials

**Comment by eduardo-mior** [comment]
Boas,

Todas essas funcionalidades são funcionalidades muito boas e muito interessantes, porém são complexas de serem desenvolvidas e exigem muito esforço.
 
Infelizmente o System não recebe mais atualizações de novas funcionalidades, apenas atualizações de melhorias e correções bugs e problemas, então isso não sera desenvolvido, a menos que outro desenvolvedor assuma o projeto.
 
Sobre um outro ponto de vista meu eu também teria algumas ponderações pra fazer:

1. Um sistema de login completo é algo muito complexo de ser feito, e hoje já existem milhares de plugins muito bons pra isso (AuthMe, nLogin etc...), não acho que o system deveria ter um sistema de login, e caso o system tivesse sistema de login iria ser bem simples.

2. Um sistema de canal (acredito eu que seja de chat) também já existem muitos plugins bons e que todo mundo já usa UltimateChat, LegendChat etc..., também não é algo que vale a pena ter no System.

3. A questão de banir os items eu não entendi exatamente oque seria, mas parece ser algo interessante, porém como eu falei, o System já não recebe mais atualizações com novos recursos.

4. O sistema de limpar o chão e as entidades também é algo que talvez valeria a pena ser estudado mas também já existem outros plugins pra isso.

5. O sistema de caixas misteriosas é algo que é bastante interessante e que é usado por quase todos os servidores, também seria util ter dentro do system. No meu perfil na gamersboard (GB) e aqui no GitHub eu já desenvolvi e publiquei gratuitamente plugins de caixas misteriosas.
