### ISSUE TITLE
Else desnecessário.

### ISSUE THREAD

**Issue by arantesxyz** [eduardo-mior/System#4]
https://github.com/eduardo-mior/System/blob/c75900e154be71cfd48457c6260b9683f94a5cb5/src/rush/recursos/gerais/EnderPearlCooldown.java#L34

**Comment by arantesxyz** [comment]
Fiz o pull request corrigindo.

https://github.com/eduardo-mior/System/pull/5

**Comment by eduardo-mior** [comment]
Na verdade esse código esta errado, o IF esta errado, ele deveria dar o put na primeira vez que joga e não deveria ter aquele remove.
